apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: 307946653240.dkr.ecr.eu-west-3.amazonaws.com/doc-platform/app:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: app-secrets
