"""add file_path to documents

Revision ID: 167c63ccb1b5
Revises: ffd73e16aee7
Create Date: 2026-07-11 17:10:03.172439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167c63ccb1b5'
down_revision: Union[str, Sequence[str], None] = 'ffd73e16aee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
